consul:
    image: progrium/consul
    ports:
      - 8600:53/tcp
      - 8600:53/udp
      - 8500:8500
      - 8400:8400
    command: -server -bootstrap agent -bind={SEU IP}  -client=0.0.0.0
    net: "host"
    restart: always

